### ISSUE TITLE
2주차. (Front)(회원) 페이지 디자인 및 만들기.

### ISSUE THREAD

**Issue by luanaeun** [miro7923/Uno-Mas#23]
- [x] 로그인 페이지
- [x] 회원가입 페이지
- [x] 회원가입시 정보 동의 페이지
- [x] 회원 탈퇴 페이지
- [x] 아이디 찾기 페이지
- [x] 비밀번호 찾기 페이지
- [x] 새로운 비밀번호로 변경 페이지
- [x] 마이페이지
- [x] 회원 정보 확인 페이지
- [x] 회원 정보 수정 페이지
- [x] 포인트 내역 페이지
- [x] 주문취소/환불 안내 페이지

**Comment by OHEUNHYEON** [comment]
노 템플릿
우리의 피땀눈물😭😭

**Comment by luanaeun** [comment]
공동구매 안내 페이지는 공동구매를 어떤식으로 할지 세부 내용 팀원과 같이 정하고 만들게요~

**Comment by miro7923** [comment]
> 공동구매 안내 페이지는 공동구매를 어떤식으로 할지 세부 내용 팀원과 같이 정하고 만들게요~

네~~
